name = "GlauberPT"
uuid = "cd1fa12f-b0ed-4c0a-9796-002e8e80502a"
version = "1.0.0-DEV"
authors = ["josej44 <jjdpbeat44@gmail.com> and contributors"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorTrains = "89893e69-996d-40b1-ba32-8ff5f34c0dd5"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Colors = "0.13.1"
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
LogarithmicNumbers = "1.4.1"
MKL = "0.7.0"
Plots = "1.41.2"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.12.3"
Statistics = "1.11.1"
TensorCast = "0.4.9"
TensorTrains = "0.13.0"
Tullio = "0.3.8"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
